"""changing composite key on sessions table

Revision ID: 38b676e687c1
Revises: d87229d68b86
Create Date: 2025-12-04 22:52:53.471299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b676e687c1'
down_revision = 'd87229d68b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('session_token', sa.String(length=440), nullable=False))
        batch_op.drop_index(batch_op.f('session_id'))
        batch_op.create_unique_constraint(None, ['session_token'])
        batch_op.drop_constraint(batch_op.f('sessions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tokens', ['token_id'], ['id'])
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', mysql.VARCHAR(length=440), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sessions_ibfk_1'), 'tokens', ['token_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('session_id'), ['session_id'], unique=True)
        batch_op.drop_column('session_token')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
