"""add avatars table

Revision ID: 402b85bc75ab
Revises: 58172b3824bd
Create Date: 2025-12-03 22:57:38.970249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402b85bc75ab'
down_revision = '58172b3824bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_avatars')
    # ### end Alembic commands ###
