"""dropping sessions

Revision ID: 7df1dd2024c8
Revises: 38b676e687c1
Create Date: 2025-12-04 23:00:03.545300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7df1dd2024c8'
down_revision = '38b676e687c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('session_token'))

    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('session_token', mysql.VARCHAR(length=440), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('sessions_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'token_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('session_token'), ['session_token'], unique=True)

    # ### end Alembic commands ###
