"""added bio col to users

Revision ID: 844d0eb21c58
Revises: 
Create Date: 2025-12-02 19:44:45.263630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844d0eb21c58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
