"""resetting sessions

Revision ID: 9f5af2e644f8
Revises: 7df1dd2024c8
Create Date: 2025-12-04 23:00:55.334413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5af2e644f8'
down_revision = '7df1dd2024c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
