"""updating rf token length to be safe

Revision ID: ad5a29d133eb
Revises: d78c38683c55
Create Date: 2025-12-07 16:12:15.633974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad5a29d133eb'
down_revision = 'd78c38683c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=mysql.VARCHAR(length=160),
               type_=sa.String(length=260),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=160),
               existing_nullable=False)

    # ### end Alembic commands ###
