"""session relationship update

Revision ID: bdc2b8d539ab
Revises: 9f5af2e644f8
Create Date: 2025-12-07 15:33:22.961047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdc2b8d539ab'
down_revision = '9f5af2e644f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', mysql.VARCHAR(length=440), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('session_token'), ['session_token'], unique=True)
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
