"""updating string length on session id

Revision ID: c588e8b2ee53
Revises: 27824b40f0ff
Create Date: 2025-12-04 21:41:27.013223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c588e8b2ee53'
down_revision = '27824b40f0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=262),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=262),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
