"""fixing relations in sessions table

Revision ID: c7d0284afef1
Revises: 9bdcd960b125
Create Date: 2025-12-03 17:24:14.893815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7d0284afef1'
down_revision = '9bdcd960b125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
