"""updating string length on session id to accommodate encryption

Revision ID: d87229d68b86
Revises: c588e8b2ee53
Create Date: 2025-12-04 22:30:45.547984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd87229d68b86'
down_revision = 'c588e8b2ee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=262),
               type_=sa.String(length=440),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=440),
               type_=mysql.VARCHAR(length=262),
               existing_nullable=False)

    # ### end Alembic commands ###
