"""update avatars table and user_fk_mixin

Revision ID: edd4eaa1354a
Revises: 0ac1205ea2bf
Create Date: 2025-12-03 22:20:30.694237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd4eaa1354a'
down_revision = '0ac1205ea2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        pass
        # batch_op.drop_constraint(batch_op.f('user_avatars_ibfk_1'), type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_avatars_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
